apiVersion: v1
kind: Namespace
metadata:
  name: last9
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: last9
  name: k8stream
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8stream
# These rules will be added to the "monitoring" role.
rules:
- apiGroups: ["*"]
  resources: ["services", "endpoints", "pods", "nodes", "events", "deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8stream
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8stream
subjects:
  - kind: ServiceAccount
    namespace: last9
    name: k8stream
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8stream-config
  namespace: last9
data:
  config.json: |
    {
      "config": {
        "uid": "719395d7-4e91-4817-a6ec-9a8ded29bebc",
        "heartbeat_hook": "https://sample.last9.io",
        "heartbeat_interval": 60,
        "batch_interval": 60,
        "batch_size": 10000,
        "sink": "s3"
      },
      "prefix": "local/test-upload",
      "aws_region": "ap-south-1",
      "aws_bucket": "last9-trials",
      "aws_profile": "last9data",
      "aws_access_key": "1",
      "aws_secret_access_key": "2",
      "kubeconfig": ""
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8stream
  namespace: last9
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8stream
        version: v1
    spec:
      serviceAccountName: k8stream
      restartPolicy: Always
      containers:
        - name: k8stream
          imagePullPolicy: Never
          image: last9inc/k8stream:a14a00f
          command: ["/app/agent"]
          args: ["--config", "/data/config.json"]
          volumeMounts:
            - mountPath: /data
              name: cfg
      volumes:
        - name: cfg
          configMap:
            name: k8stream-config
  selector:
    matchLabels:
      app: k8stream
      version: v1
